jhipster/generator-jhipster-quarkus

- package-lock.json
- package.json
Motivation:
When running JHipster, a warning message was trown becase the
`generator-hipster` dependency version is not the latest.
Modification:
Change to the latest version.
> fix: Pump to 6.7.0 version for generator-hipster

- generators/entity-server/files.js
- package.json
Use Liquibase for entities.
The blueprint reuses the upstream Liquibase and fake data.
> Use liquibase for entity migration

- README.md
- package.json
As we can't handle all the contributors name on a project such like JHipster and blueprints, I suggest to remove the contributors mentions.
I also suggest to add a link to the contributing guide from the main project. Btw we could write a specific guide for Quarkus (that can inherit from the main one).
If we want to know who has already contribute to the project, we could access to GitHub insight: https://github.com/jhipster/jhipster-quarkus/graphs/contributors
> Remove contributor references

- generators/entity/index.js
Update entity generation to match refactored entity base methods so that quarkus master works against generator-jhipster master.
This PR brings the quarkus blueprint master entity generation in sync with JHipster base. Without this entity generation fails if using the latest of both.
> Update entity generation to match refactored entity base methods

- generators/entity-server/files.js
- generators/entity-server/templates/quarkus/src/main/java/package/_partials/imperative/common/get_all.ejs
- generators/entity-server/templates/quarkus/src/main/java/package/_partials/imperative/web/get_all.ejs
- generators/entity-server/templates/quarkus/src/main/java/package/_partials/imperative/web/imports.ejs
- generators/entity-server/templates/quarkus/src/main/java/package/web/rest/vm/SortRequestVM.java.ejs
- test/entity.spec.js
Fix #95 
It should works but I open it as draft because I need to test with more scenarios.
@inngvar
> Add sorting entity feature

- generators/server/files.js
- generators/server/templates/quarkus/src/test/java/package/service/MailServiceIT.java.ejs
- test/utils/expected-files.js
fix https://github.com/jhipster/generator-jhipster-quarkus/issues/113
I'm not 100% satisfied because I would like to handle localization feature in mail and ensure our mail will be rendered in the right language. The problem is that it's seems to need more work than I expected and I don't think this is worth considered we target to finish the 1.0.0 first.
This PR at least add a test classes for MailService and improve the coverage and fix the error message quote in the issue.
Next plan should be to handle i18n properly in mail templates.
sources:
https://github.com/quarkusio/quarkus/issues/7665
https://quarkus.io/guides/qute-reference#localization
> Add a MailServiceIT.java for testing purpose

- generators/server/templates/quarkus/src/main/resources/application.properties.ejs
Quick fix to change the metrics URL.
`/management/prometheus` should be used to export metrics to prometheus
`/management/jhimetrics` is a specific endpoint to display metric in the generated application and comes from JHipster-lib (in the main project)
@danielpetisme We need this for the 0.2.0 release
> Change prometheus url to match with the JHipster one

- generators/client/files-angular.js
- generators/client/files-react.js
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/metrics/metrics.service.spec.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
- generators/server/files.js
- generators/server/templates/quarkus/src/main/java/package/web/rest/JHipsterMetricsEndpoint.java.ejs
- test/utils/expected-files.js
linked to https://github.com/jhipster/generator-jhipster-quarkus/issues/145
The jhimetrics are from the JHipster lib We can't include this lib because of Spring relative feature. I've created our own /jhimetrics endpoint.
but we can't the following metrics:
* Thread Dump (from Spring boot actuator)
* Database
* Cache
I removed the related code.
> Fix metrics page

- generators/generator-quarkus-constants.js
To update as soon as 1.11.0 is release and do preventive tests before the final version is available.
> Upgrade to Quarkus 1.11.0 

- generators/generator-quarkus-constants.js
- generators/server/templates/quarkus/build.gradle.ejs
- generators/server/templates/quarkus/gradle.properties.ejs
- generators/server/templates/quarkus/pom.xml.ejs
Beyond other things, it's needed to upgrade the Quarkus version for correct annotation processing.
> Address the issue #179 - support for graddle build

- .github/workflows/native-image.yml
- README.md
- generators/server/templates/quarkus/build.gradle.ejs
- generators/server/templates/quarkus/src/main/java/package/config/Constants.java.ejs
- generators/server/templates/quarkus/src/main/java/package/domain/User.java.ejs
- generators/server/templates/quarkus/src/main/java/package/service/UserService.java.ejs
- generators/server/templates/quarkus/src/main/resources/application.properties.ejs
- test-integration/scripts/03-run-server-native.sh
- test/server.spec.js
close https://github.com/jhipster/generator-jhipster-quarkus/issues/175
> Add a native build to ensure native is not broken

- generators/server/templates/quarkus/pom.xml.ejs
No functional changes between `0.9.4` and `1.0.0` that would be relevant for `generator-jhipster-quarkus`
We've started preparation for Quarkus 2.0 in our extension project - `quarkus-restreasy-problem:1.X.Y` is supposed to work with Quarkus 1.X, and - once Quarkus 2.0 is available - we will also bump our extension version to 2.0
> Bump quarkus-resteasy-problem extension to v1.0.0

- .github/workflows/smoke-test-imperative.yml
> Disable no database CI workflow

- generators/quarkus/templates/src/test/java/_package_/_entityPackage_/_partials/defaults.ejs
- generators/quarkus/templates/src/test/java/_package_/_entityPackage_/_partials/imports.ejs
> Fix missing enum import

- generators/quarkus/__snapshots__/generator.spec.js.snap
- generators/quarkus/generator.spec.js
- generators/quarkus/templates/gradle.properties.ejs
Add wiremock_version and testcontainers_keycloak_version to gradle.properties when authenticationType is oauth2
Addresses the _Could not get unknown property 'wiremock_version'_ issue reported by @mraible in https://github.com/jhipster/generator-jhipster-quarkus/issues/143#issue-761388190
> Fix gradle properties

- generators/quarkus/templates/pom.xml.ejs
- generators/quarkus/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.ejs
The test to include `import io.swagger.annotations.ApiModel` in an entity was failing to include the import. 
Also the swagger annotations package was missing from `pom.xml`.
> Fix swagger annotation import

- generators/quarkus/templates/src/main/java/_package_/_entityPackage_/_partials/imperative/common/get_all.ejs
- generators/quarkus/templates/src/main/java/_package_/_entityPackage_/_partials/imperative/common/search.ejs
- generators/quarkus/templates/src/main/java/_package_/_entityPackage_/_partials/imperative/web/get_all.ejs
I saw that some @RequestParams from spring resources are left , they should be migrated to QueryParams otherwise you will get compile time errors since this annotations don't exist in jax rs. 
P.S. the param itself is not used in one case but still might be used in the future I guess this is why it has been left.
> Renaming the wrongly left @RequestParam to @QueryParam

- .github/dependabot.yml
It causes dependabot to write a warning.
> Remove unknown label

- .husky/pre-commit
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```
> Fix deprecating warning from husky

- .github/workflows/smoke-test-imperative.yml
- generators/quarkus/templates/partials/data_application.properties.ejs
Thus faker data are not loaded when executing tests, and doesn't interfere with the data setup by the tests. 
Fixes #220
> test: execute liquibase with 'test' context during integration tests
