generators/server/index.js, generators/server/prompts.js
I have overwritten only a part of the server jhipster prompt. I have removed the authenticationType and nosql questions.. but maybe you can remove also other features not enabled in quarkus (cacheProvider,HibernateCache, gradle..) .
=> add custom server prompt

generators/server/templates/quarkus/.mvn/wrapper/maven-wrapper.properties, generators/server/templates/quarkus/pom.xml.ejs, generators/server/templates/quarkus/src/test/java/package/TestUtil.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/UserResourceIT.java.ejs
=> Upgrade to Quarkus 1.3.0

generators/entity-server/templates/quarkus/src/main/java/package/web/rest/EntityResource.java.ejs, generators/server/files.js, generators/server/templates/quarkus/src/main/java/package/domain/Authority.java.ejs, generators/server/templates/quarkus/src/main/java/package/domain/User.java.ejs, generators/server/templates/quarkus/src/main/java/package/service/AuthenticationService.java.ejs, generators/server/templates/quarkus/src/main/java/package/service/UserService.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/UserResource.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/AccountResourceIT.java.ejs, package-lock.json
This refactor permits to show case the usage of Hibernate Panache and the Active Record pattern (recommanded by Quarkus team) rather than the repository pattern
=> User panache for user management

generators/common/templates/quarkus/README.md.ejs, generators/server/files.js
This PR generate the standard JHipster file asis without any kind of integration with Quarkus
=> Docker file generation

generators/server/prompts.js
=> Fix build tool issue

README.md
Fix typos for issue 
https://github.com/jhipster/jhipster-quarkus/issues/69
=> QUARKUS-69 fix cd typo in README and a couple of formatting things

generators/server/files.js, generators/server/templates/quarkus/build.gradle.ejs, generators/server/templates/quarkus/pom.xml.ejs, generators/server/templates/quarkus/src/main/java/package/config/JHipsterInfo.java.ejs, generators/server/templates/quarkus/src/main/java/package/service/ManagementInfoService.java.ejs, generators/server/templates/quarkus/src/main/java/package/service/dto/ManagementInfoDTO.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/ManagementInfoResource.java.ejs, generators/server/templates/quarkus/src/main/resources/application.properties.ejs, generators/server/templates/quarkus/src/test/java/package/config/mock/JHipsterInfoMock.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/ManagementInfoResourceTest.java.ejs, package-lock.json
https://github.com/jhipster/jhipster-quarkus/issues/6
Simple integration with minimal changes
=> Feature/open api/swagger ui

generators/client/files-angular.js, generators/client/files-react.js, generators/client/index.js, generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs, generators/server/templates/quarkus/build.gradle.ejs, generators/server/templates/quarkus/partials/data_pom.xml.ejs, generators/server/templates/quarkus/partials/security_pom.xml.ejs, generators/server/templates/quarkus/pom.xml.ejs, generators/server/templates/quarkus/src/main/resources/application.properties.ejs, test/client.spec.js, test/server.spec.js
TODO:
close https://github.com/jhipster/jhipster-quarkus/issues/83
=> 83 add health check endpoint

generators/server/templates/quarkus/gradle/docker.gradle.ejs
task for building container native image added
=> jib tasks are always executed by lunching quarkusdev task  - fixed

generators/server/prompts.js, generators/server/templates/quarkus/partials/data_application.properties.ejs, test/server.spec.js, test/utils/expected-files.js
=> Enable hibernate second level cache

.github/workflows/generator.yml, package.json
related to https://github.com/jhipster/generator-jhipster/issues/12877
=> Upgrade to Node 14.15.0 LTS

generators/server/templates/quarkus/partials/data_application.properties.ejs
https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.min-size
=> Fix unknown quarkus.datasource... properties

README.md
=> Add Quarkus family member

generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs, package-lock.json, package.json
#close https://github.com/jhipster/generator-jhipster-quarkus/issues/129
=> Update to JHipster 6.10.5

cli/jhipster-quarkus.js, cli/qhipster.js, package-lock.json, package.json
inspired by https://github.com/jhipster/generator-jhipster-micronaut/blob/main/cli/mhipster.js
=> Define a cli to run the blueprint directly

generators/server/files.js, generators/server/templates/quarkus/src/main/resources/META-INF/web.xml.ejs, test/server.spec.js, test/utils/expected-files.js
=> Add web.xml file to enable h2-console servlet

generators/server/files.js, generators/server/templates/quarkus/src/main/java/package/web/rest/JHipsterLoggersEndpoint.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/vm/LoggerVM.java.ejs, test/utils/expected-files.js
=> Add loggers management

generators/common/templates/quarkus/README.md.ejs, generators/generator-quarkus-constants.js, generators/server/files.js, generators/server/templates/quarkus/pom.xml.ejs, generators/server/templates/quarkus/src/main/docker/Dockerfile.jvm.ejs, generators/server/templates/quarkus/src/main/docker/Dockerfile.legacy-jar.ejs, generators/server/templates/quarkus/src/main/docker/Dockerfile.native.ejs, generators/server/templates/quarkus/src/main/java/package/service/MailService.java.ejs, test/utils/expected-files.js
According to the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12#fast-jar-as-default we should make some modifications to the pom.xml and DockerFiles
=> Upgrade to Quarkus 1.12.0.Final

.github/workflows/generator.yml, .github/workflows/sample-app.yml
Related with https://github.com/jhipster/generator-jhipster/issues/14304
=> Update Nodejs version to 14.16.0

generators/server/files.js, generators/server/templates/quarkus/build.gradle.ejs, generators/server/templates/quarkus/gradle.properties.ejs, generators/server/templates/quarkus/pom.xml.ejs, generators/server/templates/quarkus/src/main/java/package/service/InvalidPasswordException.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/UserJWTController.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/BadRequestAlertException.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/ConstraintViolationExceptionMapper.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/EmailNotFoundException.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/ErrorConstants.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/FieldErrorVM.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/InvalidPasswordWebException.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/errors/LoginAlreadyUsedException.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/util/ResponseUtil.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/AccountResourceTest_jwt.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/UserResourceTest.java.ejs
=> Machine friendly exceptions

generators/app/index.js, generators/server/index.js, generators/server/templates/quarkus/gradle/profile_dev.gradle.ejs, generators/server/templates/quarkus/gradle/profile_prod.gradle.ejs, generators/server/templates/quarkus/pom.xml.ejs
=> Migration to JHipster v7

generators/server/templates/quarkus/pom.xml.ejs
I removed all the Jacoco dependencies and just rely on the Quarkus extension. To use Jacoco, just run `mvn verify`
Fixes #192
=> Fix Jacoco issue

generators/app/index.js, generators/entity-server/index.js, generators/entity/index.js, generators/utils.js, package.json
Fix:
- https://sonarcloud.io/project/issues?id=jhipster_jhipster-quarkus&open=AXfZp_mzvNQXsxhzEr_e&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster_jhipster-quarkus&open=AXfZp_q9vNQXsxhzEr_o&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster_jhipster-quarkus&open=AXfZp_q9vNQXsxhzEr_q&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster_jhipster-quarkus&open=AXfZp_q9vNQXsxhzEr_r&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster_jhipster-quarkus&open=AXfZp_rJvNQXsxhzEr_s&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster_jhipster-quarkus&open=AXfZp_rJvNQXsxhzEr_t&resolved=false&types=CODE_SMELL
- …
=> Sonar: fix some issues

.mocharc.js, generators/server/files.js, package-lock.json, package.json, test/__snapshots__/server.spec.js.snap, test/server.spec.js
Fixes https://github.com/jhipster/generator-jhipster-quarkus/issues/251.
=> Fix sql docker images.

generators/server/files.js, generators/server/templates/quarkus/src/main/java/package/web/rest/AuthorityResource.java.ejs, generators/server/templates/quarkus/src/main/java/package/web/rest/UserResource.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/AuthorityResourceTest.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/UserResourceTest.java.ejs, package-lock.json, test/__snapshots__/server.spec.js.snap
=> fix: Change authority resource Path mapping to align with UI

generators/server/templates/quarkus/src/main/java/package/service/MailService.java.ejs
=> fix: Handle errors while sending out emails

generators/cypress/index.js, generators/server/templates/quarkus/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/quarkus/src/main/resources/application.properties.ejs, generators/server/templates/quarkus/src/test/java/package/MockOidcServerTestResource.java.ejs
Closes #265 
Closes #195
Closes #169 
Closes #167
=> fix: Fix Keycloak authorization, cypress tests

generators/server/index.js, generators/server/templates/quarkus/gradle/profile_dev.gradle.ejs, generators/server/templates/quarkus/src/main/java/package/security/jwt/TokenProvider.java.ejs
=> fix: Gradle CI build and modernizer violations

generators/server/templates/quarkus/pom.xml.ejs, generators/server/templates/quarkus/src/main/java/package/service/UserService.java.ejs, generators/server/templates/quarkus/src/test/java/package/web/rest/UserResourceTest.java.ejs
=> fix: Do not use transactions for non-sql db

.github/workflows/generator.yml, generators/constants.js
https://quarkus.io/blog/quarkus-3-5-0-released/
=> 🚀 Quarkus 3.5.0

generators/quarkus/entity-files.js
=> Move service class to correct package

generators/quarkus/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.ejs
This fixes the issue that many-to-one relationships couldn't be loaded and saved via the API (or through the GUI).
Fixes #96
=> Fix many-to-one relationships

generators/quarkus/command.js
=> Change auth prompt type to list

.github/dependabot.yml
=> Fix dependabot gradle directory

README.md, generators/quarkus/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.ejs
=> Fix logic for including JsonIgnore annotation

generators/quarkus/command.js
Related to https://github.com/jhipster/generator-jhipster/issues/27433
=> move choices from prompt to config

README.md
Remove broken links from README badges to fix Issue #419
=> Remove broken links from README badges

generators/quarkus/__snapshots__/generator.spec.js.snap, generators/quarkus/files.js, generators/quarkus/resources/gradle/libs.versions.toml, generators/quarkus/resources/pom.xml, generators/quarkus/templates/build.gradle.ejs, generators/quarkus/templates/gradle.properties.ejs, generators/quarkus/templates/pom.xml.ejs, generators/quarkus/templates/src/main/java/_package_/config/MongockConfiguration.java.ejs, generators/quarkus/templates/src/main/java/_package_/config/dbmigrations/ChangeUnitsList.java.ejs
=> Fix #279 - repair native tests

.blueprint/generate-sample/templates/samples/microservice-jwt.jdl, .blueprint/generate-sample/templates/samples/microservice-oauth2.jdl, .blueprint/github-build-matrix/__snapshots__/generator.spec.mjs.snap, .github/workflows/smoke-test-imperative.yml, generators/quarkus/__snapshots__/generator.spec.js.snap, generators/quarkus/files.js, generators/quarkus/generator.spec.js, generators/quarkus/templates/src/test/java/_package_/ArchTest.java.ejs, generators/quarkus/templates/src/test/java/_package_/TestTokenProvider.java.ejs, generators/quarkus/templates/src/test/java/_package_/TestUtil.java.ejs, generators/quarkus/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceTest.java.ejs, generators/server/command.js
Fixes https://github.com/jhipster/generator-jhipster-quarkus/issues/434
=> Fix microservice support

generators/docker/templates/docker/app.yml.ejs
=> fix(docker): add missing configuration overrides in app.yml
